
#update the api-users.conf adding new API user object
- name: adding new API user object
  become: yes
  template:
    src: templates/api-users.conf.j2
    dest: /etc/icinga2/conf.d/api-users.conf

############################################################
#Stage 2: Setting up Icinga Web 2
#1.Install Icinga Web 2
- name: install icingaweb2 and other tools
  become: true
  apt:
        name: ['icingaweb2','libapache2-mod-php','icingacli']

#2.Step Prepare Web Setup
#create a database for icinga2web2
- name: Create database icingaweb2
  become: yes
  mysql_db:
        name: icingaweb2
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - restart mysql

#create an authentication token
- name: Get setup token.
  become: yes
  command: "icingacli setup token create"
  register: setup_token
- debug:
    var: setup_token
